#ifndef _SQL_CONST_
#define _SQL_CONST_

#define TABLE_NAME_SIZE 64
#define COL_NAME_SIZE 64
#define MAX_COLS_PER_TABLE 32
#define BTREE_CATALOG_MAX_CHILD 4
#define BTREE_SCHEMA_MAX_CHILD 4
#define BTREE_RECORD_MAX_CHILD 4

#endif
